### PR TITLE
created articles

### PR DESCRIPTION
**Pull request by Ameeshi**
Created a new branch called articles and added a model 'article' with necessary relationships and shit.

### CODE REVIEW

**Comment by Aklaran** [comment]
Hey show a little more respect to my world huh

**Comment by Aklaran** [comment]
Qapla'

**Comment by Ameeshi** [comment]
What an a**hole

**Comment by Ameeshi** [comment]
Qapla' b***h

**Comment by Aklaran** [comment]
"I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project."

Qapla'

**Comment by Aklaran** [comment]
Wow! Great qapla'!

**Pull request merged**
